### ISSUE TITLE
'<' remain in the file

### ISSUE THREAD

**Issue by obouchari** [degouville/sublime-bootstrap4#12]
When you type in ```<th5``` for example it will expand to the correct template but it keeps a ```<``` at the beginning. and ideas to avoid that? thanks.

**Comment by createbang** [comment]
+1 why is this closed?

**Comment by degouville** [comment]
See response by @raedlime in https://github.com/JasonMortonNZ/bs3-sublime-plugin/issues/99

**Comment by degouville** [comment]
@createbang Can't fix it. Please use find & replace on `<<` to `<`.

**Comment by yannis** [comment]
I fixed this for the `grid` shortcut by adding 
```
"auto_complete_triggers": [ {"selector": "text.html", "characters": "grid"} ]
```
 to Preferences-->Settings-User.
