### ISSUE TITLE
input-group expand does not work

### ISSUE THREAD

**Issue by Pokom** [degouville/sublime-bootstrap4#13]
Hey I'm not sure if this is still actively maintained. I found a bug where when I type

```
input-group
```

and tab to expand the abbreviation, nothing happens. Let me know what else I can provide to help out. I'll take a look when I get off of work if I can do some more debugging.

**Comment by degouville** [comment]
Hi @Pokom.

Can you Fork this repo, fix the bug & send a PR please?
