### ISSUE TITLE
Contributing to sublime-bootstrap4

### ISSUE THREAD

**Issue by jhuebel** [degouville/sublime-bootstrap4#33]
I'd like to contribute regularly to sublime-bootstrap4. I started working on my own snippets when I came across yours. You can see mine here:

https://github.com/jhuebel/sublime-bootstrap4-snippets/tree/master/bootstrap4

I'd like to combine my efforts with yours, rather than have a second Bootstrap 4 snippet package in Package Control.

How would you prefer me to go about that? Would you prefer I fork and submit pull requests? Or would you be willing to allow me to join as a contributor?

**Comment by jhuebel** [comment]
BTW, here is my methodology for creating snippets...

I put them in three categories:

1. a simple snippet with a few fields for doing typical edits - things like buttons, grid components (container, row, col)
2. a template/partial lifted directly from getbootstrap, which doesn't include any fields
3. other small utility snippets

It looks like you take a similar approach. I have started adding things like a comment at the beginning of the snippet with the URL to the appropriate Bootstrap docs.

**Comment by degouville** [comment]
Hi @jhuebel !

Thanks for your proposition. 
All collaboration is appreciated. 😉

Let's start w/ a PR so I can 1 of your snippets.
